# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20160901_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEntryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_position', models.PositiveIntegerField(help_text='position in which the finish line was crossed')),
                ('finish_time', models.DateTimeField(help_text='time the boat crossed the finish line')),
                ('status', models.IntegerField(choices=[(1, ''), (2, 'DNC'), (3, 'DNF'), (4, 'OCS')], default=1, help_text='special race finishing status')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Entry')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='placements',
            field=models.ManyToManyField(through='events.RaceEntryRelationship', to='events.Entry'),
        ),
    ]
