# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20160902_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceentryrelationship',
            name='finish_position',
            field=models.PositiveIntegerField(help_text='position in which the finish line was crossed', null=True),
        ),
        migrations.AlterField(
            model_name='raceentryrelationship',
            name='finish_time',
            field=models.DateTimeField(help_text='time the boat crossed the finish line', null=True),
        ),
    ]
