# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160902_0640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceentryrelationship',
            unique_together=set([('race', 'entry')]),
        ),
    ]
