# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20160902_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentryrelationship',
            name='calculated_time',
            field=models.DateTimeField(blank=True, help_text='the calculated time depending on the yardstick number', null=True),
        ),
    ]
