# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='entries',
        ),
    ]
