# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20160905_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceEntryRelationship',
            new_name='Placement',
        ),
    ]
