# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of the event', max_length=200)),
                ('mode', models.IntegerField(choices=[(1, 'Yardstick'), (2, 'Class')], default=1, help_text='type of the event either Class or Yardstick')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='first day of the event')),
                ('end_date', models.DateField(default=datetime.date.today, help_text='last day of the event')),
                ('race_count', models.PositiveIntegerField(default=1, help_text='amount of races scheduled during the event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SailingClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='full name of the sailing club', max_length=200)),
                ('abbreviation', models.CharField(blank=True, help_text='official abbreviation of the sailing club', max_length=20)),
                ('registration', models.CharField(blank=True, help_text='the registration number of the sailing club, if applicable', max_length=20)),
                ('was_organizer', models.BooleanField(default=False, help_text='if this sailing club has ever been an organizer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='the sailing club that organizes the event', on_delete=django.db.models.deletion.CASCADE, to='events.SailingClub'),
        ),
        migrations.AddField(
            model_name='event',
            name='race_committee',
            field=models.ForeignKey(help_text='the person responsible for the execution of the event', on_delete=django.db.models.deletion.CASCADE, to='events.Person'),
        ),
    ]
