# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of the boat type', max_length=200)),
                ('yardstick', models.PositiveIntegerField(default=0, help_text='official yardstick value')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type', models.ForeignKey(help_text='the boat type used by this entry', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.BoatType')),
                ('crew', models.ManyToManyField(help_text='crew members', related_name='entries_crew_in', to='events.Person')),
                ('helm', models.ForeignKey(help_text='person steering', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Person')),
            ],
        ),
    ]
