# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_boattype_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(default=1, help_text='event this entry is part of', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
    ]
