# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_entry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='crew',
            field=models.ManyToManyField(help_text='crew members', null=True, related_name='entries_crew_in', to='events.Person'),
        ),
    ]
