# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160825_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set([('event', 'number')]),
        ),
    ]
